2024-10-09 18:49:08,781 | WARNING | Неверный тип данных для объекта Runner: %s
Traceback (most recent call last):
  File "C:\Users\yanys\PycharmProjects\pythonProject\Module_12\tests_12_4.py", line 72, in test_run
    run_ = Runner(7)
  File "C:\Users\yanys\PycharmProjects\pythonProject\Module_12\tests_12_4.py", line 15, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-09 18:49:08,781 | WARNING | Неверная скорость для Runner: %s
Traceback (most recent call last):
  File "C:\Users\yanys\PycharmProjects\pythonProject\Module_12\tests_12_4.py", line 61, in test_walk
    rnr = Runner('Kate', -5)
  File "C:\Users\yanys\PycharmProjects\pythonProject\Module_12\tests_12_4.py", line 20, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
